name: Hello GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, GitHub Actions is running ðŸš€"

      - name: Show System Info
        run: |
          echo -e "\n--- OS ---"
          hostnamectl
          echo -e "\n--- CPU ---"
          lscpu | head -n 10
          echo -e "\n--- RAM ---"
          free -h
          echo -e "\n--- DISK ---"
          df -h
